(function () {
  "use strict";

  window.QUEST_SEEDS = [
    {
      "schema": "ish-quest@1",
      "meta": { "id":"omam-locked-bunkhouse","title":"The Locked Bunkhouse","unit":"Of Mice and Men — dreams, loneliness, friendship","subject":"English: Language & Literature","year":"Year 9 (MYP 4)","mode":"escape","theme":"detective","author":"ISH English","createdAt":0 },
      "story": { "introTitle":"Night on the ranch","intro":"You are locked inside the bunkhouse. George's worn notebook holds the way out. Solve each clue to lift the final latch before the others return.","outro":"The latch lifts. You step into the cool night, the dream of a little place still glowing. You read the story's heart and earned your way out." },
      "settings": { "hints":"free","hintPenalty":5,"startScore":100,"shuffleHunt":false,"showProgress":true,"timer":false,"certificate":true,"fontDefault":"standard" },
      "stations": [
        { "id":"s1","name":"The Coded Cover","icon":"🔐","narrative":"George's notebook is locked. Four words sit on the cover in a simple code.","type":"cipher","content":{ "cipherType":"caesar","shift":3,"plaintext":"MICE AND MEN" },"answer":"MICE AND MEN","acceptedAnswers":["mice and men","of mice and men"],"match":"normalized","hints":["Each letter has shifted forward in the alphabet.","Shift every letter back by 3 (D becomes A).","P→M, L→I, F→C, H→E… read it out."],"reveal":"Correct — 'Mice and Men'. Steinbeck took his title from a Robert Burns poem about plans going wrong.","points":10 },
        { "id":"s2","name":"Crooks's Word","icon":"📖","narrative":"A brass plate names the word that guards the next door.","type":"vocab-lock","content":{ "definition":"Set apart or alone; kept away from others.","sentence":"Forced to sleep apart, Crooks lived an ____ life.","firstLetter":"i" },"answer":"isolated","acceptedAnswers":["isolated","alone","set apart","separated"],"match":"normalized","hints":["The sentence says he sleeps apart from everyone.","It describes being kept away from others.","It means set apart — it begins with 'i'."],"reveal":"Yes — 'isolated' means set apart or alone. Crooks is isolated by racism as well as distance.","points":10 },
        { "id":"s3","name":"The Order of Things","icon":"🧭","narrative":"Four moments have scattered. Lay them in order to free the next bolt.","type":"sequence","content":{ "prompt":"Put these events in the order they happen.","items":["George and Lennie reach the ranch","Lennie is given a puppy","Lennie kills Curley's wife in the barn","George shoots Lennie by the river"] },"answer":"George and Lennie reach the ranch|Lennie is given a puppy|Lennie kills Curley's wife in the barn|George shoots Lennie by the river","acceptedAnswers":["George and Lennie reach the ranch|Lennie is given a puppy|Lennie kills Curley's wife in the barn|George shoots Lennie by the river"],"match":"ordered","hints":["Begin where the two men start the novel.","The gentle moment with the puppy comes before the barn.","Arrival, puppy, the barn, the river."],"reveal":"Right order. Steinbeck moves us steadily from hope to heartbreak.","points":20 },
        { "id":"s4","name":"The Gatekeeper's Question","icon":"🗝️","narrative":"The heavy door asks a careful reader one question.","type":"comprehension","content":{ "passage":"George and Lennie share a dream of a little place of their own, with rabbits and a patch of land. On the lonely ranch, the dream is the one warm thing they carry between them.","question":"In the novel, the dream of 'a little place of our own' mainly represents…","options":["a realistic retirement plan","hope and belonging in a lonely world","a joke between friends","Lennie's fear of mice"] },"answer":"hope and belonging in a lonely world","acceptedAnswers":["hope and belonging in a lonely world","b"],"match":"normalized","hints":["Think about why the dream comforts them when times are hard.","It is about more than land — it is about not being alone.","Choose the option about hope and belonging."],"reveal":"Yes — the dream stands for the hope and belonging the ranch's lonely men long for.","points":10 },
        { "id":"s5","name":"The Final Latch","icon":"🔓","narrative":"One word, spelled true, lifts the last latch.","type":"spelling-lock","content":{ "definition":"The deep sadness of being without companions — a central theme of the novel.","hintLetters":"l _ n _ l _ n _ s s" },"answer":"loneliness","acceptedAnswers":["loneliness"],"match":"exact","hints":["It is the feeling shared by Candy, Crooks and Curley's wife.","Ten letters, begins with 'lone'.","l-o-n-e-l-i-n-e-s-s."],"reveal":"LONELINESS — the ache at the centre of the book. The latch lifts. You are free.","points":15 }
      ]
    },
    {
      "schema": "ish-quest@1",
      "meta": { "id":"poets-lost-map","title":"The Poet's Lost Map","unit":"Poetic devices and figurative language","subject":"English: Language & Literature","year":"Year 8 (MYP 3)","mode":"hunt","theme":"pirate","author":"ISH English","createdAt":0 },
      "story": { "introTitle":"Verse Island","intro":"An old poet buried a chest of words on Verse Island. Five marker-stones guard it, each testing a poet's craft. Solve each to win a carved letter, then spell the treasure word.","outro":"The letters fall into place and the sand gives way — the chest creaks open, full of the poet's favourite words. You read the map of poetry and found the treasure." },
      "settings": { "hints":"free","hintPenalty":5,"startScore":100,"shuffleHunt":true,"showProgress":true,"timer":false,"certificate":true,"fontDefault":"standard","finalCode":{ "type":"join","separator":"","value":"VERSE","label":"Spell the treasure word from your carved letters" } },
      "stations": [
        { "id":"s1","name":"Stone of the Bold Compare","icon":"🪨","narrative":"The first stone hums a riddle about how poets compare.","type":"riddle","content":{ "riddle":"I compare two things, but I scorn the words 'like' and 'as'. I declare the moon IS a silver coin. Name me." },"answer":"metaphor","acceptedAnswers":["metaphor","a metaphor"],"match":"normalized","hints":["I am a figure of speech.","My quieter cousin, the simile, uses 'like' or 'as' — I do not.","I begin with 'meta'."],"reveal":"A METAPHOR — it says one thing IS another. You receive a carved letter: V.","reward":{ "fragment":"V" },"points":10 },
        { "id":"s2","name":"Stone of Repeated Sound","icon":"🪨","narrative":"Wind whistles a line of verse with one word missing.","type":"fill-blank","content":{ "text":"The technique where words begin with the same sound — 'wild and windy waves' — is called ____." },"answer":"alliteration","acceptedAnswers":["alliteration"],"match":"normalized","hints":["Listen to 'wild, windy, waves' — what repeats at the start?","It is the repeating of the first consonant sound.","It begins with 'all' and ends with 'ation'."],"reveal":"ALLITERATION — repeated opening sounds. You receive a carved letter: E.","reward":{ "fragment":"E" },"points":10 },
        { "id":"s3","name":"Stone of Tumbled Letters","icon":"🪨","narrative":"Carved letters have crumbled into a heap. Restore the poet's word.","type":"anagram","content":{ "scrambled":"MIESIL","clue":"A comparison that DOES use 'like' or 'as' — 'brave as a lion'." },"answer":"simile","acceptedAnswers":["simile"],"match":"normalized","hints":["The clue is the gentle cousin of the metaphor.","Six letters, ends in '-ile'.","Re-arrange to spell SIMILE."],"reveal":"SIMILE — a comparison using 'like' or 'as'. You receive a carved letter: R.","reward":{ "fragment":"R" },"points":10 },
        { "id":"s4","name":"Stone of Atmosphere","icon":"🪨","narrative":"A worn plaque defines the feeling a poem creates.","type":"vocab-lock","content":{ "definition":"The overall feeling or atmosphere a poem creates for the reader.","sentence":"The grey rain and silent streets gave the poem a gloomy ____.","firstLetter":"m" },"answer":"mood","acceptedAnswers":["mood","atmosphere"],"match":"normalized","hints":["It is the overall feeling the rainy scene creates.","Another word for the emotional 'air' of a poem.","Four letters, begins with 'm'."],"reveal":"MOOD — the atmosphere a poem creates. You receive a carved letter: S.","reward":{ "fragment":"S" },"points":10 },
        { "id":"s5","name":"X Marks the Spot","icon":"❌","narrative":"The final stone hides one last device in its grid of letters.","type":"hidden-word","content":{ "instruction":"One 7-letter poetic device is hidden in the top row, reading left to right. Find it.","grid":["Q W I M A G E R Y","P L O T B U R N E","S A N D R I V E R"],"targets":["imagery"] },"answer":"imagery","acceptedAnswers":["imagery"],"match":"set","hints":["A 7-letter word for language that paints pictures in your mind.","Scan the top row carefully, left to right.","It starts after the 'WI' — I-M-A-G-E-R-Y."],"reveal":"IMAGERY — descriptive language that creates pictures. You receive the last carved letter: E.","reward":{ "fragment":"E" },"points":10 }
      ]
    },
    {
      "schema": "ish-quest@1",
      "meta": { "id":"orators-sealed-archive","title":"The Orator's Sealed Archive","unit":"Persuasive writing & rhetoric — ethos, pathos, logos and rhetorical devices","subject":"English: Language & Literature","year":"Year 10 (MYP 5)","mode":"escape","theme":"detective","author":"ISH English","createdAt":0 },
      "story": { "introTitle":"The locked reading room","intro":"You are sealed inside the old debating society's archive, where the speeches of history's great persuaders are kept. The night warden has gone and the door has clicked shut. Each cabinet guards a secret of rhetoric; unlock them in turn to release the final bolt and step back into the corridor.","outro":"The final bolt slides free. You have decoded the orator's craft — appeal, device, and design — and proved you can name the tools that move an audience. The archive door swings open and the corridor lights flicker on. You read the architecture of persuasion and earned your way out." },
      "settings": { "hints":"free","hintPenalty":5,"startScore":100,"shuffleHunt":false,"showProgress":true,"timer":false,"certificate":true,"fontDefault":"standard" },
      "stations": [
        { "id":"s1","name":"The Mirror Plate","icon":"🪞","narrative":"A brass cabinet bears one word, but every letter is engraved back-to-front, as if read in a mirror.","type":"cipher","content":{ "cipherType":"reverse","plaintext":"ETHOS","prompt":"Read the mirrored word the right way round to name the appeal it labels." },"answer":"ETHOS","acceptedAnswers":["ethos","ethics","credibility"],"match":"normalized","hints":["The word has simply been written backwards — read it from right to left.","Reverse the order of the letters and a familiar rhetorical term appears.","It is the appeal to trust and character — it ends in '-thos' and begins with 'e'."],"reveal":"Correct — ETHOS. This is the appeal to the speaker's credibility and character: we believe people we judge to be trustworthy and qualified.","points":10 },
        { "id":"s2","name":"The Scattered Seal","icon":"🔠","narrative":"A wax seal has cracked and its carved letters have tumbled into a heap on the reading desk.","type":"anagram","content":{ "scrambled":"HOPTAS","clue":"The appeal to the audience's emotions — pity, anger, pride, fear." },"answer":"PATHOS","acceptedAnswers":["pathos","emotion","emotional appeal"],"match":"normalized","hints":["The clue points to the appeal that targets feelings, not logic.","Six letters; it sits beside ethos and logos as the third classical appeal.","Re-arrange the letters to spell PATHOS."],"reveal":"PATHOS — the appeal to emotion. Persuaders use vivid imagery, anecdotes and loaded words to stir how an audience feels.","points":10 },
        { "id":"s3","name":"The Misfiled Drawer","icon":"🗄️","narrative":"Four index cards have been filed together, but one device does not belong with the rest.","type":"odd-one-out","content":{ "prompt":"Three of these are persuasive or rhetorical techniques. Which card has been misfiled because it does NOT belong with them?","items":["rhetorical question","rule of three","onomatopoeia","direct address"] },"answer":"onomatopoeia","acceptedAnswers":["onomatopoeia"],"match":"normalized","hints":["Three cards are tools a speaker uses to persuade an audience.","One card is a sound device from poetry, not a way of winning over a reader.","'Buzz', 'crash' and 'hiss' are examples of the odd one out."],"reveal":"ONOMATOPOEIA is the odd one out — it imitates sounds and belongs to poetic sound devices. Rhetorical question, rule of three and direct address are all persuasive techniques.","points":15 },
        { "id":"s4","name":"The Speaker's Plaque","icon":"🎙️","narrative":"A brass plaque engraves a line from one of history's most famous persuasive speeches. Name who delivered it.","type":"attribution","content":{ "quote":"I have a dream that my four little children will one day live in a nation where they will not be judged by the colour of their skin but by the content of their character.","work":"\"I Have a Dream\" speech, 1963","options":["Martin Luther King Jr.","Winston Churchill","Nelson Mandela","Abraham Lincoln"] },"answer":"Martin Luther King Jr.","acceptedAnswers":["martin luther king jr.","martin luther king","mlk","martin luther king junior","dr martin luther king"],"match":"normalized","hints":["The speech was delivered during the American civil rights movement in 1963.","The repeated phrase 'I have a dream' is one of the most famous uses of anaphora in English.","The speaker shares his name with a major US public holiday in January."],"reveal":"Martin Luther King Jr. delivered these words in 1963. The repetition of 'I have a dream' is anaphora — a rhetorical device that builds rhythm and emotional momentum (pathos) while his moral authority supplies ethos.","points":15 },
        { "id":"s5","name":"The Final Manuscript","icon":"📜","narrative":"The last cabinet holds a short persuasive paragraph. Read it closely; the bolt releases only for the reader who can judge how it works.","type":"comprehension","content":{ "passage":"Think of the river behind our school. Think of the children who once swam there, and the herons that once fished its banks. Today it is choked with plastic. We can clean it — but only if we act now, together, before another summer is lost.","question":"Which technique is the writer relying on MOST to persuade the reader?","options":["presenting balanced statistics from both sides","appealing to emotion through vivid images and urgency","using technical scientific vocabulary","quoting expert scientists by name"] },"answer":"appealing to emotion through vivid images and urgency","acceptedAnswers":["appealing to emotion through vivid images and urgency","b","pathos","emotion"],"match":"normalized","hints":["Notice the pictures the writer paints — swimming children, fishing herons, a choked river.","There are no statistics or named experts here; the power comes from feeling and a sense of 'act now'.","This is pathos — the appeal to emotion — built from vivid imagery and urgency."],"reveal":"Correct — the paragraph leans on pathos: vivid emotive imagery ('children who once swam', 'herons that once fished') and urgency ('act now', 'before another summer is lost') rather than data or expert testimony. Recognising which appeal dominates is how you evaluate a persuasive text.","points":20 }
      ]
    }
  ];
})();
